config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :cruises
  resources :cabins
  resources :harbours
  resources :ships
  get 'travelagent/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'travelagent#index'
end

app/models/harbour.rb
class Harbour < ApplicationRecord
	validates :name, :country, :lat, :long, presence: true
end

app/controllers/harbours_controller.rb
class HarboursController < ApplicationController
  before_action :set_harbour, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found

  # GET /harbours
  # GET /harbours.json
  def index
    @harbours = Harbour.all
  end

  # GET /harbours/1
  # GET /harbours/1.json
  def show
  end

  # GET /harbours/new
  def new
    @harbour = Harbour.new
  end

  # GET /harbours/1/edit
  def edit
  end

  # POST /harbours
  # POST /harbours.json
  def create
    @harbour = Harbour.new(harbour_params)

    respond_to do |format|
      if @harbour.save
        format.html { redirect_to @harbour, notice: 'Harbour was successfully created.' }
        format.json { render :show, status: :created, location: @harbour }
      else
        format.html { render :new }
        format.json { render json: @harbour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /harbours/1
  # PATCH/PUT /harbours/1.json
  def update
    respond_to do |format|
      if @harbour.update(harbour_params)
        format.html { redirect_to @harbour, notice: 'Harbour was successfully updated.' }
        format.json { render :show, status: :ok, location: @harbour }
      else
        format.html { render :edit }
        format.json { render json: @harbour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /harbours/1
  # DELETE /harbours/1.json
  def destroy
    @harbour.destroy
    respond_to do |format|
      format.html { redirect_to harbours_url, notice: 'Harbour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_harbour
      @harbour = Harbour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def harbour_params
      params.require(:harbour).permit(:name, :country, :lat, :long)
    end
end

app/helpers/harbours_helper.rb
module HarboursHelper
end

app/views/harbours/_form.html.erb
<%= form_with(model: harbour, local: true) do |form| %>
  <% if harbour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(harbour.errors.count, "error") %> prohibited this harbour from being saved:</h2>

      <ul>
        <% harbour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/harbours/edit.html.erb
<h1>Editing Harbour</h1>

<%= render 'form', harbour: @harbour %>

<%= link_to 'Show', @harbour %> |
<%= link_to 'Back', harbours_path %>

app/views/harbours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Harbours</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Lat</th>
      <th>Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @harbours.each do |harbour| %>
      <tr>
        <td><%= harbour.name %></td>
        <td><%= harbour.country %></td>
        <td><%= harbour.lat %></td>
        <td><%= harbour.long %></td>
        <td><%= link_to 'Show', harbour %></td>
        <td><%= link_to 'Edit', edit_harbour_path(harbour) %></td>
        <td><%= link_to 'Destroy', harbour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Harbour', new_harbour_path %>

app/views/harbours/new.html.erb
<h1>New Harbour</h1>

<%= render 'form', harbour: @harbour %>

<%= link_to 'Back', harbours_path %>

app/views/harbours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @harbour.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @harbour.country %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @harbour.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @harbour.long %>
</p>

<%= link_to 'Edit', edit_harbour_path(@harbour) %> |
<%= link_to 'Back', harbours_path %>