config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :cruises
  resources :cabins
  resources :harbours
  resources :ships
  get 'travelagent/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'travelagent#index'
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :customer
  validates :exp_date, :number, :name_on_card, :organisation, presence: true
	enum organisation: {
    'American Express' => 'AmericanExpress',
    'Visa' => 'Visa',
    'MasterCard' => 'MasterCard'
  }
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound,with: :redirect_if_not_found

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
    @customers = Customer.all
  end

  # GET /credit_cards/1/edit
  def edit
    @customers = Customer.all
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)
    @credit_card.exp_date = credit_card_params['exp_date(1i)'].to_s + '/' + credit_card_params['exp_date(2i)'].to_s

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity } 
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    @credit_card.exp_date = credit_card_params['exp_date(1i)'].to_s + '/' + credit_card_params['exp_date(2i)'].to_s
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :exp_date, :name_on_card, :organisation, :customer_id)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_with(model: credit_card, local: true) do |form| %>
  <% if credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
        <% credit_card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :exp_date %>
    <%= form.date_select :exp_date, value:Date.today %>
  </div>

  <div class="field">
    <%= form.label :name_on_card %>
    <%= form.text_field :name_on_card %>
  </div>

  <div class="field">
    <%= form.label :organisation %>
    <%= form.select :organisation,CreditCard.organisations.keys, prompt: 'Select a card type' %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select(:customer_id, @customers, :id, :last_name ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credit Cards</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Exp date</th>
      <th>Name on card</th>
      <th>Organisation</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.number %></td>
        <td><%= credit_card.exp_date %></td>
        <td><%= credit_card.name_on_card %></td>
        <td><%= credit_card.organisation %></td>
        <td><%= credit_card.customer.last_name %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @credit_card.number %>
</p>

<p>
  <strong>Exp date:</strong>
  <%= @credit_card.exp_date %>
</p>

<p>
  <strong>Name on card:</strong>
  <%= @credit_card.name_on_card %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @credit_card.organisation %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @credit_card.customer.last_name %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>