config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :customers
  resources :cruises
  resources :cabins
  resources :harbours
  resources :ships
  get 'travelagent/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'travelagent#index'
end

app/models/ship.rb
class Ship < ApplicationRecord
	validates :name, :tonnage, presence: true
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found

  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
  end

  # GET /ships/new
  def new
    @ship = Ship.new
  end

  # GET /ships/1/edit
  def edit
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ships/1
  # PATCH/PUT /ships/1.json
  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :tonnage)
    end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_form.html.erb
<%= form_with(model: ship, local: true) do |form| %>
  <% if ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

      <ul>
        <% ship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tonnage %>
    <%= form.number_field :tonnage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ships/edit.html.erb
<h1>Editing Ship</h1>

<%= render 'form', ship: @ship %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tonnage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ships.each do |ship| %>
      <tr>
        <td><%= ship.name %></td>
        <td><%= ship.tonnage %></td>
        <td><%= link_to 'Show', ship %></td>
        <td><%= link_to 'Edit', edit_ship_path(ship) %></td>
        <td><%= link_to 'Destroy', ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ship', new_ship_path %>

app/views/ships/new.html.erb
<h1>New Ship</h1>

<%= render 'form', ship: @ship %>

<%= link_to 'Back', ships_path %>

app/views/ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ship.name %>
</p>

<p>
  <strong>Tonnage:</strong>
  <%= @ship.tonnage %>
</p>

<%= link_to 'Edit', edit_ship_path(@ship) %> |
<%= link_to 'Back', ships_path %>